cc_binary (
name = 'use_select',
srcs = [
    'use_select.cpp',
],
)
cc_binary (
name = 'mtlt',
srcs = [
    'mtlt.cpp',
],
extra_cppflags = [
    '-O0',
],

)
cc_binary (
name = 'unblockconnect',
srcs = [
    'unblockconnect.cpp',
],
)
cc_binary (
name = 'mytalk_client',
srcs = [
    'mytalk_client.cpp',
],
)
cc_binary (
name = 'mytalk_server',
srcs = [
    'mytalk_server.cpp',
],
)
