/* This file was generated by blade */

extern const int kSvnInfoCount;
extern const char* const kSvnInfo[];
extern const char kBuildType[];
extern const char kBuildTime[];
extern const char kBuilderName[];
extern const char kHostName[];
extern const char kCompiler[];
const int kSvnInfoCount = 1;
const char* const kSvnInfo[1] = {"commit 7a40224aed0b268524f3cb395bbf081609c8846d\n"
"Author: broadsun <onlyforsgb@163.com>\n"
"Date:   Mon Apr 1 11:22:10 2019 +0800\n"
"\n"
"    alter port show\n"
""};
const char kBuildType[] = "release";
const char kBuildTime[] = "Mon Nov 25 17:22:02 2019";
const char kBuilderName[] = "broadsun";
const char kHostName[] = "VM_0_15_centos";
const char kCompiler[] = "GCC 4.8.5";
