cc_binary (
name = 'testdup',
srcs = [
    'testdup.cpp',
],
)
cc_binary (
name = 'testsendfile',
srcs = [
    'testsendfile.cpp',
],
)
cc_binary (
name = 'testsplice',
srcs = [
    'testsplice.cpp',
],
)
cc_binary (
name = 'testtee',
srcs = [
    'testtee.cpp',
],
)
cc_binary (
name = 'testwritev',
srcs = [
    'testwritev.cpp',
],
)
