cc_binary (
name = 'byteorder',
srcs = [
    'byteorder.cpp',
],
)
cc_binary (
name = 'testlisten',
srcs = [
    'testlisten.cpp',
],
)
cc_binary (
name = 'testaccept',
srcs = [
    'testaccept.cpp',
],
)
cc_binary (
name = 'oobsend',
srcs = [
    'oobsend.cpp',
],
)
cc_binary (
name = 'oobrecv',
srcs = [
    'oobrecv.cpp',
],
)
cc_binary (
name = 'reuse_address',
srcs = [
    'reuse_address.cpp',
],
)
cc_binary (
name = 'access_daytime',
srcs = [
    'access_daytime.cpp',
],
)
